[package]
name = "tavern-master"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-sql = { version = "2.0.0", features = ["sqlite"] }
aes-gcm = "0.10.3"
base64 = "0.22.1"
keyring = "2.3.3"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
